"""empty message

Revision ID: 06fb81bcdd17
Revises: 55da28413e82
Create Date: 2020-10-31 02:16:51.496449

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '06fb81bcdd17'
down_revision = '55da28413e82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dtype', sa.String(length=31), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=31), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('animal', 'size')
    op.create_foreign_key(None, 'document', 'document_type', ['document_type'], ['dtype'])
    op.create_foreign_key(None, 'users', 'role', ['role'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'document', type_='foreignkey')
    op.add_column('animal', sa.Column('size', mysql.ENUM('cat', 'dog'), nullable=True))
    op.drop_table('role')
    op.drop_table('document_type')
    # ### end Alembic commands ###
