"""empty message

Revision ID: 53065e9aaf49
Revises: 1d03f16135a6
Create Date: 2020-10-31 15:12:29.254241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53065e9aaf49'
down_revision = '1d03f16135a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animal', sa.Column('shelter', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'animal', 'shelter', ['shelter'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'animal', type_='foreignkey')
    op.drop_column('animal', 'shelter')
    # ### end Alembic commands ###
