"""empty message

Revision ID: 56a2ed56b3f1
Revises: 23e2e2957750
Create Date: 2020-10-31 14:39:56.466586

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '56a2ed56b3f1'
down_revision = '23e2e2957750'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document', 'document_type',
               existing_type=mysql.ENUM('kal', 'shmal', 'onal'),
               nullable=False)
    op.create_foreign_key(None, 'document', 'document_type', ['document_type'], ['id'])
    op.add_column('moving', sa.Column('animal', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'moving', 'animal', ['animal'], ['id'])
    op.add_column('owner', sa.Column('animal', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'owner', 'animal', ['animal'], ['id'])
    op.add_column('shelter', sa.Column('animal', sa.Integer(), nullable=True))
    op.add_column('shelter', sa.Column('cares', sa.String(length=63), nullable=True))
    op.add_column('shelter', sa.Column('daddy', sa.String(length=127), nullable=True))
    op.add_column('shelter', sa.Column('director', sa.String(length=63), nullable=True))
    op.alter_column('shelter', 'address',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_shelter_cares'), 'shelter', ['cares'], unique=False)
    op.create_index(op.f('ix_shelter_daddy'), 'shelter', ['daddy'], unique=False)
    op.create_index(op.f('ix_shelter_director'), 'shelter', ['director'], unique=False)
    op.drop_index('ix_shelter_adm_area', table_name='shelter')
    op.drop_index('ix_shelter_clarification_of_work', table_name='shelter')
    op.drop_index('ix_shelter_departmental_affiliation', table_name='shelter')
    op.drop_index('ix_shelter_district', table_name='shelter')
    op.drop_index('ix_shelter_global_id', table_name='shelter')
    op.create_foreign_key(None, 'shelter', 'animal', ['animal'], ['id'])
    op.drop_column('shelter', 'global_id')
    op.drop_column('shelter', 'geo_data')
    op.drop_column('shelter', 'name')
    op.drop_column('shelter', 'departmental_affiliation')
    op.drop_column('shelter', 'chief_name')
    op.drop_column('shelter', 'working_hours')
    op.drop_column('shelter', 'clarification_of_work')
    op.drop_column('shelter', 'adm_area')
    op.drop_column('shelter', 'phone')
    op.drop_column('shelter', 'district')
    op.create_foreign_key(None, 'users', 'role', ['role'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.add_column('shelter', sa.Column('district', mysql.VARCHAR(length=127), nullable=False))
    op.add_column('shelter', sa.Column('phone', mysql.VARCHAR(length=15), nullable=False))
    op.add_column('shelter', sa.Column('adm_area', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('shelter', sa.Column('clarification_of_work', mysql.VARCHAR(length=511), nullable=True))
    op.add_column('shelter', sa.Column('working_hours', mysql.VARCHAR(length=511), nullable=False))
    op.add_column('shelter', sa.Column('chief_name', mysql.VARCHAR(length=127), nullable=False))
    op.add_column('shelter', sa.Column('departmental_affiliation', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('shelter', sa.Column('name', mysql.VARCHAR(length=40), nullable=True))
    op.add_column('shelter', sa.Column('geo_data', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('shelter', sa.Column('global_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'shelter', type_='foreignkey')
    op.create_index('ix_shelter_global_id', 'shelter', ['global_id'], unique=False)
    op.create_index('ix_shelter_district', 'shelter', ['district'], unique=False)
    op.create_index('ix_shelter_departmental_affiliation', 'shelter', ['departmental_affiliation'], unique=False)
    op.create_index('ix_shelter_clarification_of_work', 'shelter', ['clarification_of_work'], unique=False)
    op.create_index('ix_shelter_adm_area', 'shelter', ['adm_area'], unique=False)
    op.drop_index(op.f('ix_shelter_director'), table_name='shelter')
    op.drop_index(op.f('ix_shelter_daddy'), table_name='shelter')
    op.drop_index(op.f('ix_shelter_cares'), table_name='shelter')
    op.alter_column('shelter', 'address',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_column('shelter', 'director')
    op.drop_column('shelter', 'daddy')
    op.drop_column('shelter', 'cares')
    op.drop_column('shelter', 'animal')
    op.drop_constraint(None, 'owner', type_='foreignkey')
    op.drop_column('owner', 'animal')
    op.drop_constraint(None, 'moving', type_='foreignkey')
    op.drop_column('moving', 'animal')
    op.drop_constraint(None, 'document', type_='foreignkey')
    op.alter_column('document', 'document_type',
               existing_type=mysql.ENUM('kal', 'shmal', 'onal'),
               nullable=True)
    # ### end Alembic commands ###
