"""empty message

Revision ID: 65ec3b4b35b5
Revises: 53065e9aaf49
Create Date: 2020-10-31 15:13:31.235144

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '65ec3b4b35b5'
down_revision = '53065e9aaf49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animal', sa.Column('shelter', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'animal', 'shelter', ['shelter'], ['id'])
    op.drop_constraint('shelter_ibfk_1', 'shelter', type_='foreignkey')
    op.drop_column('shelter', 'animal')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shelter', sa.Column('animal', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('shelter_ibfk_1', 'shelter', 'animal', ['animal'], ['id'])
    op.drop_constraint(None, 'animal', type_='foreignkey')
    op.drop_column('animal', 'shelter')
    # ### end Alembic commands ###
