"""empty message

Revision ID: 67a90a0a7ce2
Revises: 
Create Date: 2020-10-30 16:25:38.179432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67a90a0a7ce2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_animal_animal_breed', table_name='animal')
    op.drop_index('ix_animal_animal_type', table_name='animal')
    op.drop_index('ix_animal_shelter', table_name='animal')
    op.create_foreign_key(None, 'animal', 'animal_type', ['animal_type'], ['id'])
    op.create_foreign_key(None, 'animal', 'shelter', ['shelter'], ['id'])
    op.create_foreign_key(None, 'animal', 'animal_breed', ['animal_breed'], ['id'])
    op.drop_index('ix_animal_breed_animal_type', table_name='animal_breed')
    op.create_foreign_key(None, 'animal_breed', 'animal_type', ['animal_type'], ['id'])
    op.drop_index('ix_pet_request_animal', table_name='pet_request')
    op.create_foreign_key(None, 'pet_request', 'animal', ['animal'], ['id'])
    op.drop_index('ix_users_shelter', table_name='users')
    op.create_foreign_key(None, 'users', 'shelter', ['shelter'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_index('ix_users_shelter', 'users', ['shelter'], unique=False)
    op.drop_constraint(None, 'pet_request', type_='foreignkey')
    op.create_index('ix_pet_request_animal', 'pet_request', ['animal'], unique=False)
    op.drop_constraint(None, 'animal_breed', type_='foreignkey')
    op.create_index('ix_animal_breed_animal_type', 'animal_breed', ['animal_type'], unique=False)
    op.drop_constraint(None, 'animal', type_='foreignkey')
    op.drop_constraint(None, 'animal', type_='foreignkey')
    op.drop_constraint(None, 'animal', type_='foreignkey')
    op.create_index('ix_animal_shelter', 'animal', ['shelter'], unique=False)
    op.create_index('ix_animal_animal_type', 'animal', ['animal_type'], unique=False)
    op.create_index('ix_animal_animal_breed', 'animal', ['animal_breed'], unique=False)
    # ### end Alembic commands ###
