"""empty message

Revision ID: b1fb585f8ff5
Revises: d96b00fc2678
Create Date: 2020-10-31 14:53:52.150472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1fb585f8ff5'
down_revision = 'd96b00fc2678'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idcard', sa.String(length=15), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=45), nullable=False),
    sa.Column('male', sa.Integer(), nullable=False),
    sa.Column('special_signs', sa.String(length=250), nullable=True),
    sa.Column('character', sa.String(length=45), nullable=True),
    sa.Column('animal_type', sa.Integer(), nullable=False),
    sa.Column('animal_breed', sa.Integer(), nullable=False),
    sa.Column('shelter', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=31), nullable=False),
    sa.Column('fur', sa.String(length=15), nullable=False),
    sa.Column('ears', sa.String(length=15), nullable=False),
    sa.Column('tail', sa.String(length=15), nullable=False),
    sa.Column('size', sa.String(length=15), nullable=False),
    sa.Column('cell', sa.Integer(), nullable=False),
    sa.Column('idmark', sa.String(length=31), nullable=False),
    sa.Column('sterilized', sa.String(length=63), nullable=False),
    sa.Column('veterinarian', sa.String(length=63), nullable=False),
    sa.Column('ready', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['animal_breed'], ['animal_breed.id'], ),
    sa.ForeignKeyConstraint(['animal_type'], ['animal_type.id'], ),
    sa.ForeignKeyConstraint(['shelter'], ['shelter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_animal_age'), 'animal', ['age'], unique=False)
    op.create_index(op.f('ix_animal_cell'), 'animal', ['cell'], unique=False)
    op.create_index(op.f('ix_animal_color'), 'animal', ['color'], unique=False)
    op.create_index(op.f('ix_animal_ears'), 'animal', ['ears'], unique=False)
    op.create_index(op.f('ix_animal_fur'), 'animal', ['fur'], unique=False)
    op.create_index(op.f('ix_animal_idcard'), 'animal', ['idcard'], unique=False)
    op.create_index(op.f('ix_animal_idmark'), 'animal', ['idmark'], unique=False)
    op.create_index(op.f('ix_animal_male'), 'animal', ['male'], unique=False)
    op.create_index(op.f('ix_animal_nickname'), 'animal', ['nickname'], unique=False)
    op.create_index(op.f('ix_animal_ready'), 'animal', ['ready'], unique=False)
    op.create_index(op.f('ix_animal_size'), 'animal', ['size'], unique=False)
    op.create_index(op.f('ix_animal_sterilized'), 'animal', ['sterilized'], unique=False)
    op.create_index(op.f('ix_animal_tail'), 'animal', ['tail'], unique=False)
    op.create_index(op.f('ix_animal_veterinarian'), 'animal', ['veterinarian'], unique=False)
    op.create_index(op.f('ix_animal_weight'), 'animal', ['weight'], unique=False)
    op.create_table('animal_photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link_to_photo', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('animal_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atype', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_animal_type_atype'), 'animal_type', ['atype'], unique=False)
    op.create_table('document_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dtype', sa.String(length=31), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=31), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shelter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=127), nullable=True),
    sa.Column('daddy', sa.String(length=127), nullable=True),
    sa.Column('director', sa.String(length=63), nullable=True),
    sa.Column('cares', sa.String(length=63), nullable=True),
    sa.Column('animal', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['animal'], ['animal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shelter_address'), 'shelter', ['address'], unique=False)
    op.create_index(op.f('ix_shelter_cares'), 'shelter', ['cares'], unique=False)
    op.create_index(op.f('ix_shelter_daddy'), 'shelter', ['daddy'], unique=False)
    op.create_index(op.f('ix_shelter_director'), 'shelter', ['director'], unique=False)
    op.create_table('animal_breed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('breed', sa.String(length=48), nullable=False),
    sa.Column('animal_type', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['animal_type'], ['animal_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catching',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('act', sa.String(length=63), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('district', sa.String(length=31), nullable=False),
    sa.Column('act1', sa.String(length=63), nullable=False),
    sa.Column('address', sa.String(length=127), nullable=False),
    sa.Column('animal', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['animal'], ['animal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catching_act'), 'catching', ['act'], unique=False)
    op.create_index(op.f('ix_catching_act1'), 'catching', ['act1'], unique=False)
    op.create_index(op.f('ix_catching_address'), 'catching', ['address'], unique=False)
    op.create_index(op.f('ix_catching_date'), 'catching', ['date'], unique=False)
    op.create_index(op.f('ix_catching_district'), 'catching', ['district'], unique=False)
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('link_to_document', sa.String(length=2000), nullable=False),
    sa.Column('animal', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['animal'], ['animal.id'], ),
    sa.ForeignKeyConstraint(['document_type'], ['document_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_date'), 'document', ['date'], unique=False)
    op.create_table('moving',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('act', sa.String(length=63), nullable=False),
    sa.Column('date', sa.String(length=31), nullable=False),
    sa.Column('reason', sa.String(length=63), nullable=False),
    sa.Column('contract', sa.String(length=63), nullable=False),
    sa.Column('animal', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['animal'], ['animal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moving_act'), 'moving', ['act'], unique=False)
    op.create_index(op.f('ix_moving_contract'), 'moving', ['contract'], unique=False)
    op.create_index(op.f('ix_moving_date'), 'moving', ['date'], unique=False)
    op.create_index(op.f('ix_moving_reason'), 'moving', ['reason'], unique=False)
    op.create_table('owner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('yurik', sa.String(length=511), nullable=False),
    sa.Column('fizik', sa.String(length=511), nullable=False),
    sa.Column('fio', sa.String(length=61), nullable=False),
    sa.Column('animal', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['animal'], ['animal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pet_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('comment', sa.String(length=250), nullable=False),
    sa.Column('animal', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['animal'], ['animal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pet_request_name'), 'pet_request', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=45), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('surname', sa.String(length=45), nullable=False),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.Column('shelter', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role'], ['role.id'], ),
    sa.ForeignKeyConstraint(['shelter'], ['shelter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_login'), 'users', ['login'], unique=False)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_surname'), 'users', ['surname'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_surname'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_login'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_pet_request_name'), table_name='pet_request')
    op.drop_table('pet_request')
    op.drop_table('owner')
    op.drop_index(op.f('ix_moving_reason'), table_name='moving')
    op.drop_index(op.f('ix_moving_date'), table_name='moving')
    op.drop_index(op.f('ix_moving_contract'), table_name='moving')
    op.drop_index(op.f('ix_moving_act'), table_name='moving')
    op.drop_table('moving')
    op.drop_index(op.f('ix_document_date'), table_name='document')
    op.drop_table('document')
    op.drop_index(op.f('ix_catching_district'), table_name='catching')
    op.drop_index(op.f('ix_catching_date'), table_name='catching')
    op.drop_index(op.f('ix_catching_address'), table_name='catching')
    op.drop_index(op.f('ix_catching_act1'), table_name='catching')
    op.drop_index(op.f('ix_catching_act'), table_name='catching')
    op.drop_table('catching')
    op.drop_table('animal_breed')
    op.drop_index(op.f('ix_shelter_director'), table_name='shelter')
    op.drop_index(op.f('ix_shelter_daddy'), table_name='shelter')
    op.drop_index(op.f('ix_shelter_cares'), table_name='shelter')
    op.drop_index(op.f('ix_shelter_address'), table_name='shelter')
    op.drop_table('shelter')
    op.drop_table('role')
    op.drop_table('document_type')
    op.drop_index(op.f('ix_animal_type_atype'), table_name='animal_type')
    op.drop_table('animal_type')
    op.drop_table('animal_photo')
    op.drop_index(op.f('ix_animal_weight'), table_name='animal')
    op.drop_index(op.f('ix_animal_veterinarian'), table_name='animal')
    op.drop_index(op.f('ix_animal_tail'), table_name='animal')
    op.drop_index(op.f('ix_animal_sterilized'), table_name='animal')
    op.drop_index(op.f('ix_animal_size'), table_name='animal')
    op.drop_index(op.f('ix_animal_ready'), table_name='animal')
    op.drop_index(op.f('ix_animal_nickname'), table_name='animal')
    op.drop_index(op.f('ix_animal_male'), table_name='animal')
    op.drop_index(op.f('ix_animal_idmark'), table_name='animal')
    op.drop_index(op.f('ix_animal_idcard'), table_name='animal')
    op.drop_index(op.f('ix_animal_fur'), table_name='animal')
    op.drop_index(op.f('ix_animal_ears'), table_name='animal')
    op.drop_index(op.f('ix_animal_color'), table_name='animal')
    op.drop_index(op.f('ix_animal_cell'), table_name='animal')
    op.drop_index(op.f('ix_animal_age'), table_name='animal')
    op.drop_table('animal')
    # ### end Alembic commands ###
